#!/bin/bash
set -e

if [[ $# -lt 1 ]]; then
    echo 'Please provide a title for your patch branch' >&2
    exit 1
fi
PATCH_TITLE=$1

for REMOTE in $(git remote); do
    URL=$(git remote get-url $REMOTE)
    if [[ $URL =~ "turt2live" ]]; then
        UPSTREAM_REPO=$REMOTE
    elif [[ $URL =~ "vector-im" ]]; then
        FORK_REPO=$REMOTE
    fi
done

function echoAndDo {
    echo "$*"
    $*
}

if [[ -z $UPSTREAM_REPO ]]; then
    echo -n 'Adding remote for upstream repo: '
    UPSTREAM_REPO=turt2live
    echoAndDo git remote add $UPSTREAM_REPO git@github.com:turt2live/matrix-bot-sdk.git
fi

if [[ -z $FORK_REPO ]]; then
    echo -n 'Adding remote for fork repo: '
    FORK_REPO=vector-im
    echoAndDo git remote add $FORK_REPO git@github.com:vector-im/matrix-bot-sdk.git
fi

git fetch $UPSTREAM_REPO
git fetch $FORK_REPO
git checkout -b $PATCH_TITLE $(git merge-base $UPSTREAM_REPO/main $FORK_REPO/element-main)

echo "Branch '$PATCH_TITLE' is now ready. Push changes to this branch when preparing a PR, and aim to merge it to both upstream and the fork."
