name: Main
on:
  push:
  pull_request:
jobs:
  # Global
  # ================================================

  eslint-16:
    name: 'ESLint Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn lint

  # Node 16
  # ================================================

  build-16:
    name: 'Build Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - run: yarn build
      - run: yarn build:examples

  tests-16:
    name: 'Tests Node 16'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 5
          command: yarn test

  # Node 18
  # ================================================

  build-14:
    name: 'Build Node 18'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn install
      - run: yarn build
      - run: yarn build:examples

  tests-14:
    name: 'Tests Node 18'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: yarn install
      - uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_minutes: 5
          command: yarn test
