name: Static Analysis
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  # Global
  # ================================================
  eslint:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'  # Target desired node version
      - run: yarn install
      - run: yarn lint

  # Node-specific
  # ================================================
  build:
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: 'Build Node ${{ matrix.node }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn build
      - run: yarn build:examples

  build-docs:
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: 'Build Docs Node ${{ matrix.node }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn docs

  tests:
    strategy:
      matrix:
        node: [ 18, 20 ]
    name: 'Tests Node ${{ matrix.node }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: yarn test
